before_script:
  - npm install

stages:
  - local-test
  
Lint Run:
  image: node:16.15.0
  stage: local-test
  tags:
      - docker
  script:
    - npm run ci:lint

Unit Test Run:
  image: node:16.15.0
  stage: local-test
  tags:
      - docker
  script:
    - npm run ci:test
